// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjawenqlewhvpixelutg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qYXdlbnFsZXdodnBpeGVsdXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTI5NzQsImV4cCI6MjA2NDY2ODk3NH0.a5YOtXGw7aPbyEdvAuksfaBzqtlmlF0gJm9owDYE79M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);